export default [
  "RIISWALKER",
  "MULTIMACH CCX",
  "PEACEBOND",
  "THE TIME-WORN SPIRE",
  "THE GUIDING SIGHT",
  "THE STEADY HAND",
  "FORGE'S PLEDGE",
  "OCCLUDED FINALITY",
  "FINITE IMPACTOR",
  "ARCHON'S THUNDER",
];
